#!/usr/bin/with-contenv bash
# Copied from the init.d stop method from non-Dockerized Plex.

echo "Stopping Plex Media Server."

kill_pids() {
  local signal="$1"
  local pids="$2"
  local pid

  while IFS= read -r pid; do
    if [ "$pid" != "" ]; then
      kill "$signal" "$pid"
    fi
  done <<< "$pids"
}

# Ask nicely
pids="$(ps -ef | grep 'Plex Media Server' | grep -v grep | awk '{print $2}')"
if [ "$pids" != "" ]; then
  kill_pids -15 "$pids"
fi

sleep 5

# Stuck
pids="$(ps -ef | grep /usr/lib/plexmediaserver | grep -v grep | awk '{print $2}')"

if [ "$pids" != "" ]; then
  kill_pids -9 "$pids"
  sleep 2
fi
