#!/usr/bin/with-contenv bash
#
# Determines if syncing config to/from persistent storage should be performed; if so:
#   Initialize the persistent storage if it's not already done,
#   then synchronize it to local storage ($HOME),
#   then delete previous persistent storage subdirectories,
#   then starts the cron service unless it is specifically deactivated by env variable.
# Finally, actually start Plex Media Server; it runs asynchronously, and this script will exit.

if /usr/local/bin/home_persistent_mounted; then
  if [ ! -f "$HOME_PERSISTENT/.last_clean" ]; then
    flock "$SYNC_STATUS_FILE" /usr/local/bin/initial_storage
  fi

  flock "$SYNC_STATUS_FILE" /usr/local/bin/sync_to_local
  flock "$SYNC_STATUS_FILE" /usr/local/bin/purge_persistent &

  if [ ! -z ${PERSISTENT_CONFIG_CRON+x} ] && [ "$PERSISTENT_CONFIG_CRON" != "FALSE" ]; then
    > "/etc/cron.d/persistent_config"
    IFS=':'
    read -ra persistent_config_cron <<< "$PERSISTENT_CONFIG_CRON"
    for i in "${persistent_config_cron[@]}"; do
      echo "$i root /usr/local/bin/periodic_sync" >> "/etc/cron.d/persistent_config"
    done
    IFS=' '

    # The line below is used to determine the s6 service directory by snagging it from PID 1.
    # It's a bit messy, but it works.
    s6-svc -u "$(ps ax | awk '{ if ( $1 == 1 ) print $NF }')/cron"
  fi
fi

echo "Starting Plex Media Server."

export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR:-${HOME}/Library/Application Support}"
export PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_INFO_VENDOR=Docker
export PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container"
export PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)

if [ ! -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" ]; then
  /bin/mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
  chown plex:plex "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
fi

exec s6-setuidgid plex /bin/sh -c 'LD_LIBRARY_PATH=/usr/lib/plexmediaserver:/usr/lib/plexmediaserver/lib /usr/lib/plexmediaserver/Plex\ Media\ Server'
