name: Helm

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master
    paths:
    - 'charts/**'
permissions:
  contents: read

jobs:

  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'plexinc/pms-docker')
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

    - name: Run Artifact Hub lint
      run: |
        wget https://github.com/artifacthub/hub/releases/download/v1.5.0/ah_1.5.0_linux_amd64.tar.gz
        echo 'ad0e44c6ea058ab6b85dbf582e88bad9fdbc64ded0d1dd4edbac65133e5c87da *ah_1.5.0_linux_amd64.tar.gz' | shasum -c
        tar -xzvf ah_1.5.0_linux_amd64.tar.gz ah
        ./ah lint -p charts/plex-media-server || exit 1
        rm -f ./ah ./ah_1.5.0_linux_amd64.tar.gz

    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          charts:
            - 'charts/plex-media-server/Chart.yaml'
            - 'charts/plex-media-server/values.yaml'

  chart:
    name: Release Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to write releases

    needs:
    - changes
    if: |
      (github.repository == 'plexinc/pms-docker') &&
      (needs.changes.outputs.charts == 'true')

    steps:
    - name: Checkout master
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      with:
        # Fetch entire history. Required for chart-releaser
        # see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
        fetch-depth: 0

    - name: Setup
      shell: bash
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f  # v1
      env:
        CR_SKIP_EXISTING: "false"
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
      with:
        charts_dir: charts
