name: Create Helm release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master
    paths:
    - charts/plex-media-server/Chart.yaml

permissions:
  contents: read

jobs:
  release:
    name: Release Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: 3.x
        check-latest: true

    - name: Set up Helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112  # v4.3.0

    - name: Set up Helm Chart Testing
      uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b  # v2.7.0

    - name: Set up Artifact Hub
      run: |
        curl --fail \
          --location https://github.com/artifacthub/hub/releases/download/v1.21.0/ah_1.21.0_linux_amd64.tar.gz \
          --output /tmp/ah.tar.gz
        echo "48d6b87b60baf4ee8fd5efbfec3bf5fb3ca783ab3f1dab625e64332b95df2a84  /tmp/ah.tar.gz" | shasum --check
        sudo tar --extract --file /tmp/ah.tar.gz --directory /usr/local/bin ah

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        # Fetch entire history. Required for chart-releaser
        # see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
        fetch-depth: 0

    - name: Lint chart
      run: |
        ct lint --config .github/linters/ct.yaml
        ah lint --path charts/plex-media-server

    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f  # v1.7.0
      env:
        CR_SKIP_EXISTING: "false"
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
      with:
        charts_dir: charts
