#!/usr/bin/with-contenv bash

# If we are debugging, enable trace
if [ "${DEBUG,,}" = "true" ]; then
  set -x
fi

. /plex-common.sh

function getPref {
  local key="$1"

  xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
}

# Get token
[ -f /etc/default/plexmediaserver ] && . /etc/default/plexmediaserver
pmsApplicationSupportDir="${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR:-${HOME}/Library/Application Support}"
prefFile="${pmsApplicationSupportDir}/Plex Media Server/Preferences.xml"
token="$(getPref "PlexOnlineToken")"

# Determine current version
if (dpkg --get-selections plexmediaserver 2> /dev/null | grep -wq "install"); then
  installedVersion=$(dpkg-query -W -f='${Version}' plexmediaserver 2> /dev/null)
else
  installedVersion="none"
fi

# Read set version
installChannel="$(cat /channel.txt)"
if [ -z "${installChannel}" ]; then
  if [ -f "/version.txt" ]; then
    echo "Migrating /version.txt to /channel.txt"
    mv /version.txt /channel.txt
    installChannel="$(cat /channel.txt)"
  else
    echo "No version specified in install. Falling back to public version."
    installChannel=public
  fi
fi

getVersionInfo "${installChannel}" "${token}" remoteVersion remoteFile
echo "Latest ${installChannel} version: $remoteVersion"

# Get updated version number
getVersionInfo "${installChannel}" "${token}" remoteVersion remoteFile

# Check if there's no update required
if [ "${remoteVersion}" = "${installedVersion}" ]; then
  echo "Server is running latest ${installChannel} version"
  exit 0
fi

if [ -z "${remoteVersion}" ] || [ -z "${remoteFile}" ]; then
  echo "Could not get update version"
  exit 1
fi

# Do update process
echo "Attempting to upgrade to: ${remoteVersion}"
installFromUrl "${remoteFile}"
